### PR TITLE
Allow the showcase player to integrate into an existing site

### PR DESCRIPTION
**Pull request by bliles**
### Changes proposed in this pull request:

Provide an optional configuration setting 'hideHeader' to allow the
Showcase player to easily integrate into the navigation of an existing site.

### CODE REVIEW

**Comment by johnluther** [comment]
Thanks, @biles. We have had a few requests for this and I have been meaning to create an issue.

**Comment by bliles** [comment]
Just noticed I'm missing a place where I need to tell the ion-content directive there is no header. Let me fix that.

**Comment by bliles** [comment]
I'd like a cleaner way to accomplish this, but the ionic framework doesn't seem to have a concept of a subheader with no header. I'm open to suggestions. Also, In order for the CSS overrides of the ionic defaults to work in jw-showcase, I need to load the jw-showcase-lib/scss/main after ionic/scss/ionic.

**Comment by ChristiaanScheermeijer** [comment]
Hi @bliles and @johnluther, I think we should rename `hideHeader` to `enableHeader` which defaults to `true` for consistency (same as `enableContinueWatching`).

It's true that Ionic (and jw-showcase-lib) doesn't have a clean way to hide the header and shift the subheader and ion-content elements without overriding SCSS. I've created a [feature branch](https://github.com/jwplayer/jw-showcase-lib/tree/feature/add-option-to-hide-header) with some SCSS changes in the header and ion-content logic.

Could you try this feature branch and verify this is what you need?

Thanks!

**Comment by bliles** [comment]
Your FB is exactly the functionality I need and a much better implementation than this PR. Thanks!

**Pull request closed without merging**
