### PR TITLE
Feature/jw8

### PR DESCRIPTION
**Pull request by pajter**
### Changes proposed in this pull request:

Fix compatibility with JW8.

### CODE REVIEW

**Comment by pajter** [comment]
I've asked the JWPlayer team if there is a better way to check for custom colors in JW8. Hopefully, this check will do until we find a better way.

**Comment by pajter** [comment]
A fix is coming. I'll leave this PR open and add another commit asap.

**Comment by ChristiaanScheermeijer** [comment]
Isn't it now forcing to use the `jw-showcase` skin?

**Comment by pajter** [comment]
I'm not sure what you mean. It's checking if the skin key is falsy, and then applies the skin. I could add an additional check for an empty object though, but I'm not sure if it's necesssary.

**Comment by ChristiaanScheermeijer** [comment]
Solved, when a default skin is being used, `jwplayer.defaults.skin` will be `false`.

**Pull request merged**
