### PR TITLE
Feature/settings page

### PR DESCRIPTION
**Pull request by brniamut**

### CODE REVIEW

**Comment by pajter** [comment]
Description text cuts off on 1024px viewport width.

screen shot 2017-09-25 at 13 09 54

**Comment by brniamut** [comment]
@pajter I removed the max height of the settings description. It shouldn't cut off now

**Comment by brniamut** [comment]
@ChristiaanScheermeijer the user-icon has been removed

**Comment by brniamut** [comment]
Breakpoint of buttons not working on mobile

**Comment by brniamut** [comment]
Breakpoint of buttons fixed. A css class was not written correct

**Comment by pajter** [comment]
Vertical alignment of the slider navigation is a bit off.

screen shot 2017-09-25 at 13 44 39

**Comment by brniamut** [comment]
@pajter The same shelf components are used all over the site and I didn't change anything. I will discuss with the designer if this was intended. I guess not but I'll ask to be certain.

**Comment by pajter** [comment]
@brniamut Looks good now, thanks! 👍

**Pull request merged**
