### PR TITLE
Feat/auth and signing

### PR DESCRIPTION
**Pull request by RWOverdijk**
### Changes proposed in this pull request:

Adds firebase features and signing

### CODE REVIEW

**Comment by ChristiaanScheermeijer** [comment]
ok to test

**Comment by RWOverdijk** [comment]
@ChristiaanScheermeijer Fixes :)

**Comment by ChristiaanScheermeijer** [comment]
@RWOverdijk to master?

**Comment by RWOverdijk** [comment]
@ChristiaanScheermeijer Old PR. I'll change it.

**Pull request merged**
